episodes: 800
running_average: 50
discount_factor: 0.85
learning_rate: 1e-4
epsilon_0: 0.999
epsilon_inf: 0.05
epsilon_decay: 0.99999
batch_size: 64
replay_buffer_size: 20000
target_update_freq: 2000
cutting_value: 1.0
use_cer: true
show_plot: true