episodes: 800
running_average: 50
discount_factor: 0.84
learning_rate: 1e-4
epsilon_0: 0.999
epsilon_inf: 0.05
epsilon_decay: 0.99999
batch_size: 100
replay_buffer_size: 17000
target_update_freq: 170
cutting_value: 1.0
use_cer: true
show_plot: false
dueling: true